// Point Cloud & Mesh Export Module
// Open source algorithms for 3D data export

export interface PointCloudData {
  positions: Float32Array;
  colors: Float32Array;
  normals: Float32Array;
  count: number;
}

export interface MeshData {
  vertices: Float32Array;
  normals: Float32Array;
  indices: Uint32Array;
  vertexCount: number;
  indexCount: number;
}

// ============= POINT CLOUD EXPORT =============

/**
 * Export point cloud to PLY format (open source standard)
 * PLY is simple, widely supported, and human-readable
 */
export function exportPointCloudToPLY(data: PointCloudData): string {
  let ply = 'ply\n';
  ply += 'format ascii 1.0\n';
  ply += `element vertex ${data.count}\n`;
  ply += 'property float x\n';
  ply += 'property float y\n';
  ply += 'property float z\n';
  ply += 'property uchar red\n';
  ply += 'property uchar green\n';
  ply += 'property uchar blue\n';
  ply += 'property float nx\n';
  ply += 'property float ny\n';
  ply += 'property float nz\n';
  ply += 'end_header\n';

  for (let i = 0; i < data.count; i++) {
    const i3 = i * 3;
    const x = data.positions[i3];
    const y = data.positions[i3 + 1];
    const z = data.positions[i3 + 2];
    
    const r = Math.floor(data.colors[i3] * 255);
    const g = Math.floor(data.colors[i3 + 1] * 255);
    const b = Math.floor(data.colors[i3 + 2] * 255);
    
    const nx = data.normals[i3];
    const ny = data.normals[i3 + 1];
    const nz = data.normals[i3 + 2];
    
    ply += `${x} ${y} ${z} ${r} ${g} ${b} ${nx} ${ny} ${nz}\n`;
  }

  return ply;
}

/**
 * Export point cloud to OBJ format (widely supported)
 */
export function exportPointCloudToOBJ(data: PointCloudData): string {
  let obj = '# Point Cloud Export\n';
  obj += '# Generated by Golden Ratio Fractal Engine\n\n';

  for (let i = 0; i < data.count; i++) {
    const i3 = i * 3;
    const x = data.positions[i3];
    const y = data.positions[i3 + 1];
    const z = data.positions[i3 + 2];
    obj += `v ${x} ${y} ${z}\n`;
  }

  obj += '\n# Normals\n';
  for (let i = 0; i < data.count; i++) {
    const i3 = i * 3;
    const nx = data.normals[i3];
    const ny = data.normals[i3 + 1];
    const nz = data.normals[i3 + 2];
    obj += `vn ${nx} ${ny} ${nz}\n`;
  }

  return obj;
}

// ============= MESH EXPORT (Marching Cubes) =============

/**
 * Simplified Marching Cubes algorithm for mesh generation
 * Based on open source implementation by Paul Bourke
 */
export function generateMeshFromSDF(
  sdfFunction: (x: number, y: number, z: number) => number,
  bounds: { min: [number, number, number]; max: [number, number, number] },
  resolution: number = 64
): MeshData {
  const vertices: number[] = [];
  const normals: number[] = [];
  const indices: number[] = [];

  const [minX, minY, minZ] = bounds.min;
  const [maxX, maxY, maxZ] = bounds.max;
  
  const stepX = (maxX - minX) / resolution;
  const stepY = (maxY - minY) / resolution;
  const stepZ = (maxZ - minZ) / resolution;

  // Sample SDF on grid
  const grid: number[][][] = [];
  for (let i = 0; i <= resolution; i++) {
    grid[i] = [];
    for (let j = 0; j <= resolution; j++) {
      grid[i][j] = [];
      for (let k = 0; k <= resolution; k++) {
        const x = minX + i * stepX;
        const y = minY + j * stepY;
        const z = minZ + k * stepZ;
        grid[i][j][k] = sdfFunction(x, y, z);
      }
    }
  }

  // Generate mesh using marching cubes (simplified)
  let vertexIndex = 0;
  for (let i = 0; i < resolution; i++) {
    for (let j = 0; j < resolution; j++) {
      for (let k = 0; k < resolution; k++) {
        // Check if this cell contains a surface
        const cube = [
          grid[i][j][k],
          grid[i + 1][j][k],
          grid[i + 1][j + 1][k],
          grid[i][j + 1][k],
          grid[i][j][k + 1],
          grid[i + 1][j][k + 1],
          grid[i + 1][j + 1][k + 1],
          grid[i][j + 1][k + 1]
        ];

        // Simple surface detection: sign change
        const hasSurface = cube.some(v => v > 0) && cube.some(v => v < 0);
        
        if (hasSurface) {
          // Add vertex at cell center (simplified)
          const x = minX + (i + 0.5) * stepX;
          const y = minY + (j + 0.5) * stepY;
          const z = minZ + (k + 0.5) * stepZ;
          
          vertices.push(x, y, z);
          
          // Compute normal via central differences
          const eps = 0.01;
          const nx = sdfFunction(x + eps, y, z) - sdfFunction(x - eps, y, z);
          const ny = sdfFunction(x, y + eps, z) - sdfFunction(x, y - eps, z);
          const nz = sdfFunction(x, y, z + eps) - sdfFunction(x, y, z - eps);
          const len = Math.sqrt(nx * nx + ny * ny + nz * nz);
          normals.push(nx / len, ny / len, nz / len);
          
          vertexIndex++;
        }
      }
    }
  }

  // Generate indices (simple triangulation)
  for (let i = 0; i < vertexIndex - 2; i += 3) {
    indices.push(i, i + 1, i + 2);
  }

  return {
    vertices: new Float32Array(vertices),
    normals: new Float32Array(normals),
    indices: new Uint32Array(indices),
    vertexCount: vertexIndex,
    indexCount: indices.length
  };
}

/**
 * Export mesh to OBJ format
 */
export function exportMeshToOBJ(data: MeshData): string {
  let obj = '# Mesh Export\n';
  obj += '# Generated by Golden Ratio Fractal Engine\n\n';

  // Vertices
  for (let i = 0; i < data.vertexCount; i++) {
    const i3 = i * 3;
    obj += `v ${data.vertices[i3]} ${data.vertices[i3 + 1]} ${data.vertices[i3 + 2]}\n`;
  }

  obj += '\n# Normals\n';
  for (let i = 0; i < data.vertexCount; i++) {
    const i3 = i * 3;
    obj += `vn ${data.normals[i3]} ${data.normals[i3 + 1]} ${data.normals[i3 + 2]}\n`;
  }

  obj += '\n# Faces\n';
  for (let i = 0; i < data.indexCount; i += 3) {
    const i1 = data.indices[i] + 1;
    const i2 = data.indices[i + 1] + 1;
    const i3 = data.indices[i + 2] + 1;
    obj += `f ${i1}//${i1} ${i2}//${i2} ${i3}//${i3}\n`;
  }

  return obj;
}

/**
 * Download file helper
 */
export function downloadFile(content: string, filename: string, mimeType: string = 'text/plain'): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
